config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sql_templates
  get 'cms/*page', to: 'cms#respond'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sql_template.rb
class SqlTemplate < ApplicationRecord
  validates :body, :path, presence: true
  validates :format, inclusion: Mime::SET.symbols.map(&:to_s)
  validates :locale, inclusion: I18n.available_locales.map(&:to_s)
  validates :handler, inclusion: ActionView::Template::Handlers.extensions.map(&:to_s)

  after_save do
    SqlTemplate::Resolver.instance.clear_cache
  end

  class Resolver < ActionView::Resolver
    require 'singleton'
    include Singleton

    protected

    def find_templates(name, prefix, partial, details)
      conditions = {
        path: normalize_path(name, prefix),
        locale: normalize_array(details[:locale]).first,
        format: normalize_array(details[:formats]).first,
        handler: normalize_array(details[:handlers]).first,
        partial: partial || false
      }

      ::SqlTemplate.where(conditions).map do |record|
        initialize_template(record)
      end
    end

    # Normalize name and prefix, so the tuple ["index", "users"] becomes
    # "users/index" and the tuple ['template', nil] becomes "template"
    def normalize_path(name, prefix)
      prefix.present? ? "#{prefix}/#{name}" : name
    end

    # Normalize arrays by converting all symbols to strings
    def normalize_array(array)
      array.map(&:to_s)
    end

    # initialize an ActionView::Template based on the record found
    def initialize_template(record)
      source = record.body
      identifier = "SqlTemplate - #{record.id} - #{record.path.inspect}"
      handler = ActionView::Template.registered_template_handler(record.handler)

      details = {
        format: Mime[record.format],
        updated_at: record.updated_at,
        virtual_path: virtual_path(record.path, record.partial)
      }

      ActionView::Template.new(source, identifier, handler, details)
    end

    # make paths like users/users become users/_user for partials
    def virtual_path(path, partial)
      return path unless partial
      if index = path.rindex("/")
        path.insert(index + 1, "_")
      else
        "_#{path}"
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cms_controller.rb
class CmsController < ActionController::Metal
  include ActionController::Rendering
  include AbstractController::Helpers
  prepend_view_path ::SqlTemplate::Resolver.instance
  helper CmsHelper

  def respond
    render template: params[:page]
  end
end

app/controllers/sql_templates_controller.rb
class SqlTemplatesController < ApplicationController
  before_action :set_sql_template, only: [:show, :edit, :update, :destroy]

  # GET /sql_templates
  # GET /sql_templates.json
  def index
    @sql_templates = SqlTemplate.all
  end

  # GET /sql_templates/1
  # GET /sql_templates/1.json
  def show
  end

  # GET /sql_templates/new
  def new
    @sql_template = SqlTemplate.new
  end

  # GET /sql_templates/1/edit
  def edit
  end

  # POST /sql_templates
  # POST /sql_templates.json
  def create
    @sql_template = SqlTemplate.new(sql_template_params)

    respond_to do |format|
      if @sql_template.save
        format.html { redirect_to @sql_template, notice: 'Sql template was successfully created.' }
        format.json { render :show, status: :created, location: @sql_template }
      else
        format.html { render :new }
        format.json { render json: @sql_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sql_templates/1
  # PATCH/PUT /sql_templates/1.json
  def update
    respond_to do |format|
      if @sql_template.update(sql_template_params)
        format.html { redirect_to @sql_template, notice: 'Sql template was successfully updated.' }
        format.json { render :show, status: :ok, location: @sql_template }
      else
        format.html { render :edit }
        format.json { render json: @sql_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sql_templates/1
  # DELETE /sql_templates/1.json
  def destroy
    @sql_template.destroy
    respond_to do |format|
      format.html { redirect_to sql_templates_url, notice: 'Sql template was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sql_template
      @sql_template = SqlTemplate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sql_template_params
      params.require(:sql_template).permit(:body, :path, :format, :locale, :handler, :partial)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  append_view_path SqlTemplate::Resolver.instance
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cms_helper.rb
module CmsHelper
end

app/helpers/sql_templates_helper.rb
module SqlTemplatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Templater</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sql_templates/_form.html.erb
<%= form_with(model: sql_template, local: true) do |form| %>
  <% if sql_template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sql_template.errors.count, "error") %> prohibited this sql_template from being saved:</h2>

      <ul>
      <% sql_template.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :path %>
    <%= form.text_field :path %>
  </div>

  <div class="field">
    <%= form.label :format %>
    <%= form.text_field :format %>
  </div>

  <div class="field">
    <%= form.label :locale %>
    <%= form.text_field :locale %>
  </div>

  <div class="field">
    <%= form.label :handler %>
    <%= form.text_field :handler %>
  </div>

  <div class="field">
    <%= form.label :partial %>
    <%= form.check_box :partial %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sql_templates/edit.html.erb
<h1>Editing Sql Template</h1>

<%= render 'form', sql_template: @sql_template %>

<%= link_to 'Show', @sql_template %> |
<%= link_to 'Back', sql_templates_path %>

app/views/sql_templates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sql Templates</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>Path</th>
      <th>Format</th>
      <th>Locale</th>
      <th>Handler</th>
      <th>Partial</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sql_templates.each do |sql_template| %>
      <tr>
        <td><%= sql_template.body %></td>
        <td><%= sql_template.path %></td>
        <td><%= sql_template.format %></td>
        <td><%= sql_template.locale %></td>
        <td><%= sql_template.handler %></td>
        <td><%= sql_template.partial %></td>
        <td><%= link_to 'Show', sql_template %></td>
        <td><%= link_to 'Edit', edit_sql_template_path(sql_template) %></td>
        <td><%= link_to 'Destroy', sql_template, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sql Template', new_sql_template_path %>

app/views/sql_templates/new.html.erb
<h1>New Sql Template</h1>

<%= render 'form', sql_template: @sql_template %>

<%= link_to 'Back', sql_templates_path %>

app/views/sql_templates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @sql_template.body %>
</p>

<p>
  <strong>Path:</strong>
  <%= @sql_template.path %>
</p>

<p>
  <strong>Format:</strong>
  <%= @sql_template.format %>
</p>

<p>
  <strong>Locale:</strong>
  <%= @sql_template.locale %>
</p>

<p>
  <strong>Handler:</strong>
  <%= @sql_template.handler %>
</p>

<p>
  <strong>Partial:</strong>
  <%= @sql_template.partial %>
</p>

<%= link_to 'Edit', edit_sql_template_path(@sql_template) %> |
<%= link_to 'Back', sql_templates_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>